DROP TABLE SERIE CASCADE CONSTRAINT;
CREATE TABLE SERIE
(
  ANNEE NUMBER(4) CONSTRAINT NN_SERIE_ANNEE NOT NULL,
  TITRE VARCHAR(50) CONSTRAINT NN_SERIE_TITRE NOT NULL,
  PAYS VARCHAR(50) CONSTRAINT CK_SERIE_PAYS CHECK( RPAD(PAYS,1)= UPPER(RPAD(PAYS,1))),
  CONSTRAINT  PK_SERIE   PRIMARY KEY  (ANNEE,TITRE)
);

DROP TABLE PERSONNE CASCADE CONSTRAINT;
CREATE TABLE PERSONNE
(
  NOM_PER VARCHAR(10) CONSTRAINT NN_PERSONNE_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_PERSONNE_PRENOM NOT NULL,
  DATE_INSCRIPTION DATE ,
  AGE NUMBER(3) CONSTRAINT CK_PERSONNE_AGE CHECK(AGE > 0),
  SEXE CHAR(4) CONSTRAINT CK_PERSONNE_SEX CHECK (SEXE  IN ('F','M')),
  CONSTRAINT PK_PERSONNE PRIMARY KEY (NOM_PER,PRENOM_PER)
);

DROP TABLE NOTER_SERIE CASCADE CONSTRAINT;
CREATE TABLE NOTER_SERIE
(
  DATE_NOTE DATE,
  NOTE NUMBER(4) CONSTRAINT CK_NOTER_SER_NOT CHECK ( NOTE BETWEEN 0 AND 10 ),
  COMMENTAIRE VARCHAR(50),
  ANNEE NUMBER(4) CONSTRAINT NN_NOTER_SERIE_ANNEE NOT NULL,
  TITRE VARCHAR(50) CONSTRAINT NN_NOTER_SERIE_TITRE NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_NOTER_SERIE_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_NOTER_SERIE_PRENOM NOT NULL,
  CONSTRAINT PK_NOTER_SERIE PRIMARY KEY (ANNEE,TITRE,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_NOTER_SERIE_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE(ANNEE,TITRE) ,
  CONSTRAINT FK_NOTER_SERIE_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES  PERSONNE(NOM_PER,PRENOM_PER)
);

DROP TABLE EST_CREE CASCADE CONSTRAINT;
CREATE TABLE EST_CREE
(
  ANNEE NUMBER(4) CONSTRAINT NN_EST_CREE_ANNEE NOT NULL,
  TITRE VARCHAR(50) CONSTRAINT NN_EST_CREE_TITRE NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_EST_CREE_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_EST_CREE_PRENOM NOT NULL,
  DATE_CREATION DATE CONSTRAINT NN_EST_CREE_DATE_CREATION NOT NULL,
  CONSTRAINT PK_EST_CREE PRIMARY KEY (ANNEE,TITRE,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_EST_CREE_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE(ANNEE,TITRE) ,
  CONSTRAINT FK_EST_CREE_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES PERSONNE(NOM_PER,PRENOM_PER)
);


DROP TABLE EST_PRODUIT
CASCADE CONSTRAINT;
CREATE TABLE EST_PRODUIT
(
  ANNEE NUMBER(4) CONSTRAINT NN_EST_PRODUIT_ANNEE NOT NULL,
  TITRE VARCHAR(50) CONSTRAINT NN_EST_PRODUIT_TITRE NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_EST_PRODUIT_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_EST_PRODUIT_PRENOM NOT NULL,
  DATE_PRODUCTION DATE CONSTRAINT NN_EST_PRODUIT_DATE_PROD NOT NULL,
  CONSTRAINT PK_EST_PRODUIT PRIMARY KEY (ANNEE,TITRE,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_EST_PRODUIT_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE(ANNEE,TITRE) ,
  CONSTRAINT FK_EST_PRODUIT_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES  PERSONNE(NOM_PER,PRENOM_PER)
);


DROP TABLE EPISODE CASCADE CONSTRAINT;
CREATE TABLE EPISODE
(
  TITRE_EPS VARCHAR(50) CONSTRAINT NN_EPISODE_TITRE_EPS NOT NULL,
  DURE NUMBER CONSTRAINT NN_SERIE_DURE NOT NULL,
  DATE_DIFFUSION DATE CONSTRAINT NN_EPISODE_DATE_DIFF NOT NULL,
  RESUMEE VARCHAR(200) ,
  ANNEE NUMBER(4) CONSTRAINT NN_EPISODE_ANNEE NOT NULL,
  TITRE VARCHAR(50) CONSTRAINT NN_EPISONDE_TITRE NOT NULL,
  NUM_SAISON NUMBER(5) CONSTRAINT NN_EPISODE_NUM_SAISON NOT NULL,
  CONSTRAINT PK_EPISODE PRIMARY KEY (TITRE_EPS),
  CONSTRAINT FK_EPISODE_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE(ANNEE,TITRE),
  CONSTRAINT FK_EPISODE_SAISON FOREIGN KEY  (NUM_SAISON) REFERENCES SAISON(NUM_SAISON)
);

DROP TABLE GENRE CASCADE CONSTRAINT;
CREATE TABLE GENRE (
  NOM_GENRE VARCHAR(50) CONSTRAINT PK_GENRE_NOM PRIMARY KEY
);

DROP TABLE SAISON CASCADE CONSTRAINT;
CREATE TABLE SAISON (
  NUM_SAISON NUMBER(5) CONSTRAINT PK_SAISON_NUM PRIMARY KEY
);

DROP TABLE EST_GENRE CASCADE CONSTRAINT;
CREATE TABLE EST_GENRE (
  NOM_GENRE VARCHAR(50),
  ANNEE NUMBER(4) ,
  TITRE VARCHAR(50) ,
  CONSTRAINT PK_EST_GENRE PRIMARY KEY(NOM_GENRE,ANNEE,TITRE),
  CONSTRAINT FK_EST_GENRE_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE,
  CONSTRAINT FK_EST_GENRE_GENRE FOREIGN KEY (NOM_GENRE) REFERENCES GENRE
);


DROP TABLE NOTER_EPISODE CASCADE CONSTRAINT;
CREATE TABLE NOTER_EPISODE
(
  DATE_NOTE_EPS DATE,
  NOTE_EPS NUMBER(4) CONSTRAINT CK_NOTER_EPI_NOT CHECK ( NOTE_EPS BETWEEN 0 AND 10),
  COMMENTAIRE_EPS VARCHAR(500),
  TITRE_EPS VARCHAR(50) CONSTRAINT NN_NOTER_EPISODE_TITRE NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_NOTER_EPISODE_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_NOTER_EPISODE_PRENOM NOT NULL,
  CONSTRAINT PK_NOTER_EPISODE PRIMARY KEY (TITRE_EPS,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_NOTER_EPISODE_SERIE FOREIGN KEY (TITRE_EPS) REFERENCES EPISODE(TITRE_EPS) ,
  CONSTRAINT FK_NOTER_EPISODE_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES  PERSONNE(NOM_PER,PRENOM_PER)
);


DROP TABLE EST_ACTEUR CASCADE CONSTRAINT;
CREATE TABLE EST_ACTEUR
(
  TITRE_EPS VARCHAR(50) CONSTRAINT NN_ACTEUR_TITRE_EPS NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_ACTEUR_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_ACTEUR_PRENOM NOT NULL,
  CONSTRAINT PK_ACTEUR PRIMARY KEY (TITRE_EPS,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_ACTEUR_EPISODE FOREIGN KEY (TITRE_EPS) REFERENCES EPISODE,
  CONSTRAINT FK_ACTEUR_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES  PERSONNE(NOM_PER,PRENOM_PER)
);


DROP TABLE EST_REALISATEUR CASCADE CONSTRAINT;
CREATE TABLE EST_REALISATEUR
(
  TITRE_EPS VARCHAR(50) CONSTRAINT NN_REALISATEUR_TITRE_EPS NOT NULL,
  NOM_PER VARCHAR(10) CONSTRAINT NN_REALISATEUR_NOM NOT NULL,
  PRENOM_PER VARCHAR(20) CONSTRAINT NN_REALISATEUR_PRENOM NOT NULL,
  CONSTRAINT PK_REALISATEUR PRIMARY KEY (TITRE_EPS,NOM_PER,PRENOM_PER),
  CONSTRAINT FK_REALISATEUR_EPISODE FOREIGN KEY (TITRE_EPS) REFERENCES EPISODE,
  CONSTRAINT FK_REALISATEUR_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES PERSONNE(NOM_PER,PRENOM_PER)
);

 DROP TABLE MESSAGES  CASCADE CONSTRAINT;
 CREATE TABLE MESSAGES(
    ID_MSG   NUMBER(5) CONSTRAINT PK_MESSAGES PRIMARY KEY,
    ID_MSG_PARENT NUMBER(5),
    ANNEE NUMBER(4) CONSTRAINT NN_MESSAGES_ANNEE NOT NULL,
    TITRE VARCHAR(50) CONSTRAINT NN_NMESSAGES_TITRE NOT NULL,
    NOM_PER VARCHAR(10) CONSTRAINT NN_MESSAGES_NOM NOT NULL,
    PRENOM_PER VARCHAR(20) CONSTRAINT NN_MESSAGES_PRENOM NOT NULL,
    TEXTE VARCHAR2(1000),
    TITRE_MSG VARCHAR2(100),
    DATE_MESSAGE_ENVOYE DATE CONSTRAINT NN_MESSAGES_DATE_MSG_ENVOY NOT NULL,
    CONSTRAINT FK_MESSAGES_MESSAGES FOREIGN KEY (ID_MSG_PARENT) REFERENCES MESSAGES(ID_MSG),
    CONSTRAINT FK_MESSAGES_SERIE FOREIGN KEY (ANNEE,TITRE) REFERENCES SERIE(ANNEE,TITRE) ,
    CONSTRAINT FK_MESSAGES_PERSO FOREIGN KEY (NOM_PER,PRENOM_PER) REFERENCES  PERSONNE(NOM_PER,PRENOM_PER)
 );
